// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTAnalitic.Infrastructure;

namespace PTAnalitic.Infrastructure.Migrations
{
    [DbContext(typeof(PTDbContext))]
    [Migration("20200109144450_ProductHistoryModified")]
    partial class ProductHistoryModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PTAnalitic.Core.Model.ProductHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("PointOfSale");

                    b.Property<string>("ProductId");

                    b.Property<long>("Stock");

                    b.HasKey("Id");

                    b.ToTable("ProductHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
